from .src.auto_fix_engine import (
    AutoFixEngine,
    LoopResult,
    FullPatch,
    ZonePatch,
    CorrectionEntry,
    FixType,
    classify_issue,
    compute_fix,
    patch_to_css,
    full_patch_to_css,
    apply_css_patch,
    run_correction_loop,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_TARGET_SCORE,
    ZONE_PRIORITY,
)

__all__ = [
    "AutoFixEngine",
    "LoopResult",
    "FullPatch",
    "ZonePatch",
    "CorrectionEntry",
    "FixType",
    "classify_issue",
    "compute_fix",
    "patch_to_css",
    "full_patch_to_css",
    "apply_css_patch",
    "run_correction_loop",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_TARGET_SCORE",
    "ZONE_PRIORITY",
]
