"""
document_templates — EURKAI branded document template objects.

Each template object wraps a document object class with brand-specific defaults,
and can generate a ready-to-use Python install script for any project.

Templates:
    BrandDefinition         — brand tokens (palette, typography, issuer, footer)
    InvoiceTemplate         — InvoiceDoc pre-wired to a brand
    QuoteTemplate           — QuoteDoc pre-wired to a brand
    PurchaseOrderTemplate   — PurchaseOrderDoc pre-wired to a brand
    TextDocTemplate         — TextDoc pre-wired to a brand
    SheetDocTemplate        — SheetDoc pre-wired to a brand (legacy compat)

Usage:
    brand = BrandDefinition(
        name="EURKAI SAS",
        design={"palette": {"primary": "#0f172a", "accent": "#6366f1"}},
        issuer=DocumentIssuer(name="EURKAI SAS", ...),
    )
    tmpl = InvoiceTemplate(brand=brand)
    doc  = tmpl.create(doc_number="FAC-001", doc_date="2026-01-01", client=..., items=[...])
    html = doc.render()
    script = tmpl.generate_install_script()  # Python code ready to drop into any project
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel

from .document_base import (
    DocumentIssuer, DocumentClient, DocumentLineItem,
    DocumentPageHeader, DocumentPageFooter,
)
from .invoice_doc        import InvoiceDoc, InvoiceDocInput, BankDetails
from .quote_doc          import QuoteDoc, QuoteDocInput
from .purchase_order_doc import PurchaseOrderDoc, PurchaseOrderDocInput, DeliveryInfo
from .text_doc           import TextDoc, TextDocInput, TextBlock
from .sheet_doc          import SheetDoc, SheetDocInput, IssuerSchema, ClientSchema, LineItem


# ── BrandDefinition ───────────────────────────────────────────────────────────

class BrandDefinition(BaseModel):
    """
    Canonical brand token container.
    A single BrandDefinition is shared across all templates of a project.
    """
    name: str                                  # brand display name
    design: Dict[str, Any] = {}               # palette, typography, spacing
    issuer: Optional[DocumentIssuer] = None    # pre-filled issuer for business docs
    page_header: Optional[DocumentPageHeader] = None
    page_footer: Optional[DocumentPageFooter] = None
    default_currency: str = "EUR"
    default_payment_terms: Optional[str] = (
        "Paiement à 30 jours nets à compter de la date d'émission."
    )
    default_late_payment_clause: Optional[str] = (
        "En cas de retard de paiement, des pénalités de 3× le taux d'intérêt légal "
        "seront appliquées, ainsi qu'une indemnité forfaitaire de 40 € pour frais de recouvrement."
    )
    bank_details: Optional[BankDetails] = None

    def design_repr(self) -> str:
        """Produce a Python dict literal representation of design tokens."""
        import json
        return json.dumps(self.design, indent=4, ensure_ascii=False)


# ── InvoiceTemplate ───────────────────────────────────────────────────────────

class InvoiceTemplate:
    """InvoiceDoc pre-wired to a BrandDefinition."""

    def __init__(self, brand: BrandDefinition):
        self.brand = brand

    def create(
        self,
        doc_number: str,
        doc_date: str,
        client: DocumentClient,
        items: List[DocumentLineItem],
        due_date: Optional[str] = None,
        notes: Optional[str] = None,
        payment_terms: Optional[str] = None,
        bank_details: Optional[BankDetails] = None,
        purchase_order_ref: Optional[str] = None,
    ) -> InvoiceDoc:
        b = self.brand
        return InvoiceDoc(InvoiceDocInput(
            doc_number=doc_number,
            doc_date=doc_date,
            due_date=due_date,
            currency=b.default_currency,
            issuer=b.issuer or DocumentIssuer(name=b.name),
            client=client,
            items=items,
            payment_terms=payment_terms or b.default_payment_terms,
            late_payment_clause=b.default_late_payment_clause,
            bank_details=bank_details or b.bank_details,
            notes=notes,
            page_header=b.page_header,
            page_footer=b.page_footer,
            design=b.design,
            purchase_order_ref=purchase_order_ref,
        ))

    def generate_install_script(self, output_var: str = "html") -> str:
        b = self.brand
        issuer_repr = _issuer_repr(b.issuer, b.name)
        design_repr = b.design_repr()
        bank_repr = _bank_repr(b.bank_details)
        pt = repr(b.default_payment_terms)
        return (
f"# ── {b.name} — Invoice generator\n"
f"# Generated by EURKAI InvoiceTemplate. Drop into any Python project.\n"
f"# Requires: pip install pydantic\n"
f"\n"
f"import sys\n"
f"from pathlib import Path\n"
f"sys.path.insert(0, str(Path(__file__).parent))\n"
f"\n"
f"from document_objects import (\n"
f"    InvoiceDoc, InvoiceDocInput, BankDetails,\n"
f"    DocumentIssuer, DocumentClient, DocumentLineItem,\n"
f")\n"
f"\n"
f"BRAND_DESIGN = {design_repr}\n"
f"\n"
f"ISSUER = DocumentIssuer(**{issuer_repr})\n"
f"\n"
f"BANK = {bank_repr}\n"
f"\n"
f"\n"
f"def make_invoice(\n"
f"    doc_number: str,\n"
f"    doc_date: str,\n"
f"    client: DocumentClient,\n"
f"    items: list,\n"
f"    due_date: str = None,\n"
f"    notes: str = None,\n"
f") -> str:\n"
f"    doc = InvoiceDoc(InvoiceDocInput(\n"
f"        doc_number=doc_number,\n"
f"        doc_date=doc_date,\n"
f"        due_date=due_date,\n"
f"        currency={repr(b.default_currency)},\n"
f"        issuer=ISSUER,\n"
f"        client=client,\n"
f"        items=items,\n"
f"        payment_terms={pt},\n"
f"        bank_details=BANK,\n"
f"        notes=notes,\n"
f"        design=BRAND_DESIGN,\n"
f"    ))\n"
f"    return doc.render()\n"
f"\n"
f"\n"
f"if __name__ == '__main__':\n"
f"    client = DocumentClient(name='Client Test', email='client@example.com')\n"
f"    items = [DocumentLineItem(description='Prestation', quantity=1, unit_price=1000.0)]\n"
f"    {output_var} = make_invoice('FAC-001', '2026-01-01', client, items)\n"
f"    Path('invoice_output.html').write_text({output_var})\n"
f"    print('Invoice written to invoice_output.html')\n"
        )


# ── QuoteTemplate ─────────────────────────────────────────────────────────────

class QuoteTemplate:
    """QuoteDoc pre-wired to a BrandDefinition."""

    def __init__(self, brand: BrandDefinition):
        self.brand = brand

    def create(
        self,
        doc_number: str,
        doc_date: str,
        client: DocumentClient,
        items: List[DocumentLineItem],
        validity_date: Optional[str] = None,
        notes: Optional[str] = None,
        conditions: Optional[str] = None,
        show_acceptance_block: bool = True,
    ) -> QuoteDoc:
        b = self.brand
        kwargs = dict(
            doc_number=doc_number,
            doc_date=doc_date,
            validity_date=validity_date,
            currency=b.default_currency,
            issuer=b.issuer or DocumentIssuer(name=b.name),
            client=client,
            items=items,
            notes=notes,
            show_acceptance_block=show_acceptance_block,
            page_header=b.page_header,
            page_footer=b.page_footer,
            design=b.design,
        )
        if conditions is not None:
            kwargs["conditions"] = conditions
        return QuoteDoc(QuoteDocInput(**kwargs))

    def generate_install_script(self, output_var: str = "html") -> str:
        b = self.brand
        issuer_repr = _issuer_repr(b.issuer, b.name)
        design_repr = b.design_repr()
        return (
f"# ── {b.name} — Quote generator\n"
f"# Generated by EURKAI QuoteTemplate. Drop into any Python project.\n"
f"\n"
f"import sys\n"
f"from pathlib import Path\n"
f"sys.path.insert(0, str(Path(__file__).parent))\n"
f"\n"
f"from document_objects import (\n"
f"    QuoteDoc, QuoteDocInput,\n"
f"    DocumentIssuer, DocumentClient, DocumentLineItem,\n"
f")\n"
f"\n"
f"BRAND_DESIGN = {design_repr}\n"
f"ISSUER = DocumentIssuer(**{issuer_repr})\n"
f"\n"
f"\n"
f"def make_quote(\n"
f"    doc_number: str,\n"
f"    doc_date: str,\n"
f"    client: DocumentClient,\n"
f"    items: list,\n"
f"    validity_date: str = None,\n"
f"    notes: str = None,\n"
f") -> str:\n"
f"    doc = QuoteDoc(QuoteDocInput(\n"
f"        doc_number=doc_number,\n"
f"        doc_date=doc_date,\n"
f"        validity_date=validity_date,\n"
f"        currency={repr(b.default_currency)},\n"
f"        issuer=ISSUER,\n"
f"        client=client,\n"
f"        items=items,\n"
f"        notes=notes,\n"
f"        design=BRAND_DESIGN,\n"
f"    ))\n"
f"    return doc.render()\n"
f"\n"
f"\n"
f"if __name__ == '__main__':\n"
f"    client = DocumentClient(name='Client Test', email='client@example.com')\n"
f"    items = [DocumentLineItem(description='Prestation', quantity=1, unit_price=500.0)]\n"
f"    {output_var} = make_quote('DEV-001', '2026-01-01', client, items, validity_date='2026-02-01')\n"
f"    Path('quote_output.html').write_text({output_var})\n"
f"    print('Quote written to quote_output.html')\n"
        )


# ── PurchaseOrderTemplate ─────────────────────────────────────────────────────

class PurchaseOrderTemplate:
    """PurchaseOrderDoc pre-wired to a BrandDefinition."""

    def __init__(self, brand: BrandDefinition):
        self.brand = brand

    def create(
        self,
        doc_number: str,
        doc_date: str,
        client: DocumentClient,
        items: List[DocumentLineItem],
        delivery: Optional[DeliveryInfo] = None,
        order_ref: Optional[str] = None,
        supplier_ref: Optional[str] = None,
        notes: Optional[str] = None,
        payment_terms: Optional[str] = None,
    ) -> PurchaseOrderDoc:
        b = self.brand
        return PurchaseOrderDoc(PurchaseOrderDocInput(
            doc_number=doc_number,
            doc_date=doc_date,
            currency=b.default_currency,
            issuer=b.issuer or DocumentIssuer(name=b.name),
            client=client,
            items=items,
            delivery=delivery,
            order_ref=order_ref,
            supplier_ref=supplier_ref,
            payment_terms=payment_terms or b.default_payment_terms,
            notes=notes,
            page_header=b.page_header,
            page_footer=b.page_footer,
            design=b.design,
        ))

    def generate_install_script(self, output_var: str = "html") -> str:
        b = self.brand
        issuer_repr = _issuer_repr(b.issuer, b.name)
        design_repr = b.design_repr()
        pt = repr(b.default_payment_terms)
        return (
f"# ── {b.name} — Purchase order generator\n"
f"# Generated by EURKAI PurchaseOrderTemplate. Drop into any Python project.\n"
f"\n"
f"import sys\n"
f"from pathlib import Path\n"
f"sys.path.insert(0, str(Path(__file__).parent))\n"
f"\n"
f"from document_objects import (\n"
f"    PurchaseOrderDoc, PurchaseOrderDocInput, DeliveryInfo,\n"
f"    DocumentIssuer, DocumentClient, DocumentLineItem,\n"
f")\n"
f"\n"
f"BRAND_DESIGN = {design_repr}\n"
f"ISSUER = DocumentIssuer(**{issuer_repr})\n"
f"\n"
f"\n"
f"def make_purchase_order(\n"
f"    doc_number: str,\n"
f"    doc_date: str,\n"
f"    supplier: DocumentClient,\n"
f"    items: list,\n"
f"    delivery: DeliveryInfo = None,\n"
f"    order_ref: str = None,\n"
f"    notes: str = None,\n"
f") -> str:\n"
f"    doc = PurchaseOrderDoc(PurchaseOrderDocInput(\n"
f"        doc_number=doc_number,\n"
f"        doc_date=doc_date,\n"
f"        currency={repr(b.default_currency)},\n"
f"        issuer=ISSUER,\n"
f"        client=supplier,\n"
f"        items=items,\n"
f"        delivery=delivery,\n"
f"        order_ref=order_ref,\n"
f"        payment_terms={pt},\n"
f"        notes=notes,\n"
f"        design=BRAND_DESIGN,\n"
f"    ))\n"
f"    return doc.render()\n"
f"\n"
f"\n"
f"if __name__ == '__main__':\n"
f"    supplier = DocumentClient(name='Supplier Test', email='supplier@example.com')\n"
f"    items = [DocumentLineItem(description='Matériel', quantity=1, unit_price=200.0)]\n"
f"    {output_var} = make_purchase_order('BC-001', '2026-01-01', supplier, items)\n"
f"    Path('po_output.html').write_text({output_var})\n"
f"    print('Purchase order written to po_output.html')\n"
        )


# ── TextDocTemplate ───────────────────────────────────────────────────────────

class TextDocTemplate:
    """TextDoc pre-wired to a BrandDefinition."""

    def __init__(self, brand: BrandDefinition):
        self.brand = brand

    def create(
        self,
        title: str,
        blocks: List[TextBlock],
        doc_number: Optional[str] = None,
        author: Optional[str] = None,
        date: Optional[str] = None,
    ) -> TextDoc:
        b = self.brand
        return TextDoc(TextDocInput(
            title=title,
            blocks=blocks,
            doc_number=doc_number,
            author=author,
            date=date,
            design=b.design,
        ))

    def generate_install_script(self, output_var: str = "html") -> str:
        b = self.brand
        design_repr = b.design_repr()
        return (
f"# ── {b.name} — Text document generator\n"
f"# Generated by EURKAI TextDocTemplate. Drop into any Python project.\n"
f"\n"
f"import sys\n"
f"from pathlib import Path\n"
f"sys.path.insert(0, str(Path(__file__).parent))\n"
f"\n"
f"from document_objects import TextDoc, TextDocInput, TextBlock\n"
f"\n"
f"BRAND_DESIGN = {design_repr}\n"
f"\n"
f"\n"
f"def make_text_doc(title: str, blocks: list, author: str = None, date: str = None) -> str:\n"
f"    doc = TextDoc(TextDocInput(\n"
f"        title=title,\n"
f"        blocks=blocks,\n"
f"        author=author,\n"
f"        date=date,\n"
f"        design=BRAND_DESIGN,\n"
f"    ))\n"
f"    return doc.render()\n"
f"\n"
f"\n"
f"if __name__ == '__main__':\n"
f"    blocks = [\n"
f"        TextBlock(type='heading', content='Introduction'),\n"
f"        TextBlock(type='paragraph', content='Contenu du document.'),\n"
f"    ]\n"
f"    {output_var} = make_text_doc('Mon document', blocks, author={repr(b.name)})\n"
f"    Path('textdoc_output.html').write_text({output_var})\n"
f"    print('TextDoc written to textdoc_output.html')\n"
        )


# ── SheetDocTemplate ──────────────────────────────────────────────────────────

class SheetDocTemplate:
    """SheetDoc pre-wired to a BrandDefinition. Legacy compatibility path."""

    def __init__(self, brand: BrandDefinition):
        self.brand = brand

    def create(
        self,
        doc_type: str,
        doc_number: str,
        doc_date: str,
        issuer: IssuerSchema,
        client: ClientSchema,
        items: List[LineItem],
        notes: Optional[str] = None,
    ) -> SheetDoc:
        return SheetDoc(SheetDocInput(
            doc_type=doc_type,
            doc_number=doc_number,
            doc_date=doc_date,
            issuer=issuer,
            client=client,
            items=items,
            notes=notes,
            design=self.brand.design,
        ))

    def generate_install_script(self, output_var: str = "html") -> str:
        b = self.brand
        design_repr = b.design_repr()
        return (
f"# ── {b.name} — SheetDoc generator (legacy)\n"
f"# Generated by EURKAI SheetDocTemplate. Drop into any Python project.\n"
f"\n"
f"import sys\n"
f"from pathlib import Path\n"
f"sys.path.insert(0, str(Path(__file__).parent))\n"
f"\n"
f"from document_objects import (\n"
f"    SheetDoc, SheetDocInput, IssuerSchema, ClientSchema, LineItem,\n"
f")\n"
f"\n"
f"BRAND_DESIGN = {design_repr}\n"
f"\n"
f"\n"
f"def make_sheet_doc(doc_type, doc_number, doc_date, issuer, client, items, notes=None):\n"
f"    doc = SheetDoc(SheetDocInput(\n"
f"        doc_type=doc_type,\n"
f"        doc_number=doc_number,\n"
f"        doc_date=doc_date,\n"
f"        issuer=issuer,\n"
f"        client=client,\n"
f"        items=items,\n"
f"        notes=notes,\n"
f"        design=BRAND_DESIGN,\n"
f"    ))\n"
f"    return doc.render()\n"
f"\n"
f"\n"
f"if __name__ == '__main__':\n"
f"    issuer = IssuerSchema(name={repr(b.name)}, email='contact@example.com')\n"
f"    client = ClientSchema(name='Client Test')\n"
f"    items = [LineItem(description='Service', quantity=1, unit_price=500.0)]\n"
f"    {output_var} = make_sheet_doc('invoice', 'FAC-001', '2026-01-01', issuer, client, items)\n"
f"    Path('sheetdoc_output.html').write_text({output_var})\n"
f"    print('SheetDoc written to sheetdoc_output.html')\n"
        )


# ── Private helpers ───────────────────────────────────────────────────────────

def _issuer_repr(issuer: Optional[DocumentIssuer], brand_name: str) -> str:
    if issuer is None:
        return f'{{"name": "{brand_name}"}}'
    data = issuer.model_dump(exclude_none=True)
    import json
    return json.dumps(data, ensure_ascii=False)


def _bank_repr(bank: Optional[BankDetails]) -> str:
    if bank is None:
        return "None"
    data = bank.model_dump(exclude_none=True)
    import json
    return f"BankDetails(**{json.dumps(data, ensure_ascii=False)})"
